name: 🛡️ Proxy Anti-Ban 100%
on:
  workflow_dispatch

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Instalando
        run: |
          sudo apt update -y
          sudo apt install -y wget curl
          wget -q https://raw.githubusercontent.com/serjs/socks5-server/master/install.sh
          chmod +x install.sh
          sudo ./install.sh -u ADM -p JEICO777 -P 8888 --anti-detect
          echo "✅ TU IP ES:"
          curl ifconfig.me
